# Generated by Django 5.2.16 on 2026-09-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='metric_content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
