# Generated by Django 5.2.16 on 2026-09-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_seed_duplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='ai_requested',
            field=models.BooleanField(default=False),
        ),
    ]
